# Generated by Django 4.0.3 on 2022-03-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.CharField(choices=[('C', 'PENDING'), ('P', 'COMPLETED')], max_length=10),
        ),
    ]
